using UnityEngine;
using System.Collections;
using UnityEngine.Audio;
using System.Collections.Generic;

public class AudioController : MonoBehaviour {

	public GameObject backgroundMusic;
	public GameObject voiceOutput;

	public Dictionary<string, string> keyAudioList = new Dictionary<string, string>();


	// Use this for initialization
	void Start () {
		setupKeyAudioList ();
	}
	
	// Update is called once per frame
	void Update () {
	}

	public void setupVoice(string key){
		string audioSource;
		keyAudioList.TryGetValue (key, out audioSource);
		AudioClip clip = Resources.Load ("Audio/Voice/"+audioSource)as AudioClip;
		voiceOutput.GetComponent<AudioSource> ().clip = clip;
		voiceOutput.GetComponent<AudioSource>().Play();
	}

	void setupKeyAudioList(){
		keyAudioList.Add ("entry", "jane_bath_1");
		keyAudioList.Add ("mirror1", "jane_bath_2");
		keyAudioList.Add ("mirror2", "jane_bath_3");
		keyAudioList.Add ("paper", "jane_bath_4");
		keyAudioList.Add ("theory1", "jane_bath_5");

		keyAudioList.Add ("welcome1", "michael_house_1_1");
		keyAudioList.Add ("welcome2", "jane_house_1_1");
		keyAudioList.Add ("welcome3", "michael_house_1_2");
		keyAudioList.Add ("welcome4", "jane_house_1_2");
		keyAudioList.Add ("welcome5", "michael_house_1_3");
		keyAudioList.Add ("diningRoom", "michael_house_1_4");
		keyAudioList.Add ("scar1_1", "jane_house_1_3");
		keyAudioList.Add ("scar1_2", "michael_house_1_5");
		keyAudioList.Add ("scar2_1", "michael_house_1_6");
		keyAudioList.Add ("scar2_2", "jane_house_1_5");		
		keyAudioList.Add ("scar2_3", "michael_house_1_7");		
		keyAudioList.Add ("scar2_4", "jane_house_1_6");		
		keyAudioList.Add ("theory2", "jane_house_1_4");		
		keyAudioList.Add ("friends1", "jane_house_1_7");		
		keyAudioList.Add ("friends2", "michael_house_1_8");		
		keyAudioList.Add ("family1", "jane_house_1_8");		
		keyAudioList.Add ("family2", "michael_house_1_9");		
		keyAudioList.Add ("family3", "jane_house_1_9");		
		keyAudioList.Add ("family4", "michael_house_1_10");		
		keyAudioList.Add ("daughter1", "jane_house_1_10");		
		keyAudioList.Add ("daughter2", "michael_house_1_11");		
		keyAudioList.Add ("daughter3", "jane_house_1_11");		
		keyAudioList.Add ("daughter4", "michael_house_1_12");		
		keyAudioList.Add ("daughter5", "jane_house_1_12");		
		keyAudioList.Add ("daughter6", "michael_house_1_13");		
		keyAudioList.Add ("daughter7", "jane_house_1_13");		
		keyAudioList.Add ("piano1", "michael_house_1_14");		
		keyAudioList.Add ("piano2", "jane_house_1_14");		
		keyAudioList.Add ("piano3", "michael_house_1_15");		
		keyAudioList.Add ("daughter2_1", "jane_house_1_15");		
		keyAudioList.Add ("daughter2_2", "michael_house_1_16");		
		keyAudioList.Add ("daughter2_3", "michael_house_1_17");		
		keyAudioList.Add ("daughter2_4", "jane_house_1_16");		
		keyAudioList.Add ("daughter2_5", "michael_house_1_18");		
		keyAudioList.Add ("daughter2_6", "jane_house_1_17");		
		keyAudioList.Add ("daughter2_7", "michael_house_1_19");		
		keyAudioList.Add ("missingPictureFound", "jane_house_1_18");		
		keyAudioList.Add ("picture1", "jane_house_1_19");		
		keyAudioList.Add ("picture2", "michael_house_1_20");		
		keyAudioList.Add ("picture3", "jane_house_1_20");
		keyAudioList.Add ("picture4", "michael_house_1_21");
		keyAudioList.Add ("familyAlbum1_1", "jane_house_1_21");		
		keyAudioList.Add ("familyAlbum1_2", "michael_house_1_22");		
		keyAudioList.Add ("noteMonolog", "jane_house_1_22");		
		keyAudioList.Add ("conservatory1", "jane_house_1_23");		
		keyAudioList.Add ("conservatory2", "michael_house_1_23");		
		keyAudioList.Add ("conservatory3", "jane_house_1_24");		
		keyAudioList.Add ("glassTable1", "jane_house_1_25");		
		keyAudioList.Add ("glassTable2", "michael_house_1_24");		
		keyAudioList.Add ("glassTable3", "jane_house_1_26");		
		keyAudioList.Add ("glassTable4", "michael_house_1_25");		
		keyAudioList.Add ("glassTable5", "jane_house_1_27");		
		keyAudioList.Add ("childsroom1", "michael_house_1_26");		
		keyAudioList.Add ("childsroom2", "jane_house_1_28");		
		keyAudioList.Add ("childsroom3", "michael_house_1_27");		
		keyAudioList.Add ("guestroom1", "michael_house_1_28");		
		keyAudioList.Add ("guestroom2", "jane_house_1_29");		
		keyAudioList.Add ("guestroom3", "michael_house_1_29");		
		keyAudioList.Add ("guestroom4", "jane_house_1_30");		
		keyAudioList.Add ("workroom", "michael_house_1_30");		
		keyAudioList.Add ("bookshelf", "jane_house_1_31");		
		keyAudioList.Add ("bedroom1", "michael_house_1_31");		
		keyAudioList.Add ("bedroom2", "jane_house_1_32");		
		keyAudioList.Add ("adressBook1", "jane_house_1_33");		
		keyAudioList.Add ("adressBook2", "michael_house_1_32");		
		keyAudioList.Add ("scene1Ending1", "michael_house_1_33");		
		keyAudioList.Add ("scene1Ending2", "jane_house_1_34");		
		keyAudioList.Add ("scene1Ending3", "michael_house_1_34");
		//text house 2
		keyAudioList.Add ("dizzy1", "jane_house_2_1");		
		keyAudioList.Add ("paulaPhoneDialog1", "paula_house_2_1");
		keyAudioList.Add ("paulaIntroduction1", "jane_house_2_2");
		keyAudioList.Add ("paulaIntroduction2", "paula_house_2_2");
		keyAudioList.Add ("paulaIntroduction3", "jane_house_2_3");
		keyAudioList.Add ("paulaIntroduction4", "paula_house_2_3");
		keyAudioList.Add ("paulaIntroduction5", "jane_house_2_4");
		keyAudioList.Add ("paulaIntroduction6", "paula_house_2_4");
		keyAudioList.Add ("paulaIntroduction7", "jane_house_2_5");
		keyAudioList.Add ("paulaIntroduction8", "paula_house_2_5");
		keyAudioList.Add ("paulaIntroduction9", "jane_house_2_6");
		keyAudioList.Add ("paulaPhoneCall1", "jane_house_2_7");
		keyAudioList.Add ("paulaPhoneCall2", "paula_house_2_6");
		keyAudioList.Add ("paulaPhoneCall3", "jane_house_2_8");
		keyAudioList.Add ("paulaPhoneCall4", "paula_house_2_7");
		keyAudioList.Add ("paulaPhoneCall5", "jane_house_2_9");
		keyAudioList.Add ("paulaPhoneCall6", "paula_house_2_8");
		keyAudioList.Add ("paulaPhoneCall7", "jane_house_2_10");
		keyAudioList.Add ("paulaIntroduction2_1", "jane_house_2_11");
		keyAudioList.Add ("paulaIntroduction2_2", "paula_house_2_9");
		keyAudioList.Add ("paulaIntroduction2_3", "jane_house_2_12");
		keyAudioList.Add ("paulaIntroduction2_4", "paula_house_2_10");
		keyAudioList.Add ("paulaIntroduction2_5", "jane_house_2_13");
		keyAudioList.Add ("scare1", "jane_house_2_14");
		keyAudioList.Add ("scare2", "michael_house_2_1");
		keyAudioList.Add ("scare3", "jane_house_2_15");
		keyAudioList.Add ("scare4", "michael_house_2_2");
		keyAudioList.Add ("father1", "jane_house_2_16");
		keyAudioList.Add ("father2", "michael_house_2_3");
		keyAudioList.Add ("father3", "jane_house_2_17");
		keyAudioList.Add ("father4", "michael_house_2_4");
		keyAudioList.Add ("father5", "jane_house_2_18");
		keyAudioList.Add ("mother1", "jane_house_2_19");
		keyAudioList.Add ("mother2", "michael_house_2_5");
		keyAudioList.Add ("mother3", "jane_house_2_20");
		keyAudioList.Add ("mother4", "michael_house_2_6");
		keyAudioList.Add ("mother5", "jane_house_2_21");
		keyAudioList.Add ("mother6", "michael_house_2_7");
		keyAudioList.Add ("mother7", "jane_house_2_22");
		keyAudioList.Add ("mother8", "michael_house_2_8");
		keyAudioList.Add ("mother9", "jane_house_2_23");
		keyAudioList.Add ("bedroom3", "jane_house_2_24");
		keyAudioList.Add ("adressbookLost", "jane_house_2_25");
		keyAudioList.Add ("bedtime1", "michael_house_2_9");
		keyAudioList.Add ("bedtime2", "jane_house_2_26");
		keyAudioList.Add ("bedtime3", "michael_house_2_10");
		keyAudioList.Add ("lostAdressBook1", "jane_house_2_27");
		keyAudioList.Add ("lostAdressBook2", "michael_house_2_11");
		keyAudioList.Add ("lostAdressBook3", "jane_house_2_28");
		keyAudioList.Add ("lostAdressBook4", "michael_house_2_12");
		keyAudioList.Add ("lostAdressBook5", "jane_house_2_29");
		keyAudioList.Add ("lostAdressBook6", "michael_house_2_13");
		keyAudioList.Add ("lostAdressBook7", "jane_house_2_30");
		keyAudioList.Add ("lostAdressBook8", "michael_house_2_14");
		keyAudioList.Add ("lostAdressBook9", "jane_house_2_31");
		keyAudioList.Add ("lostAdressBook10", "michael_house_2_15");
		keyAudioList.Add ("lostAdressBook11", "jane_house_2_32");
		//text house 3
		keyAudioList.Add ("dizzy2", "jane_house_3_1");
		keyAudioList.Add ("theory3", "jane_house_3_2");
		keyAudioList.Add ("pills1", "jane_house_3_3");
		keyAudioList.Add ("pills2", "michael_house_3_1");
		keyAudioList.Add ("pills3", "jane_house_3_4");
		keyAudioList.Add ("pills4", "michael_house_3_2");
		keyAudioList.Add ("pills5", "jane_house_3_5");
		keyAudioList.Add ("pills6", "michael_house_3_3");
		keyAudioList.Add ("pills7", "jane_house_3_6");
		keyAudioList.Add ("pills8", "michael_house_3_4");
		keyAudioList.Add ("callDoc", "jane_house_3_7");
		keyAudioList.Add ("information1", "jane_house_3_8");
		keyAudioList.Add ("information2", "information_1");
		keyAudioList.Add ("information3", "jane_house_3_9");
		keyAudioList.Add ("information2_1", "information_2");
		keyAudioList.Add ("information2_2", "jane_house_3_10");
		keyAudioList.Add ("meloffCall1", "information_3");
		keyAudioList.Add ("meloffCall2", "meloff_1");
		keyAudioList.Add ("meloffCall3", "jane_house_3_11");
		keyAudioList.Add ("meloffCall4", "meloff_2");
		keyAudioList.Add ("meloffCall5", "jane_house_3_12");
		keyAudioList.Add ("meloffCall6", "meloff_3");
		keyAudioList.Add ("meloffCall7", "jane_house_3_13");
		keyAudioList.Add ("meloffCall8", "meloff_4");
		keyAudioList.Add ("meloffCall9", "jane_house_3_14");
		keyAudioList.Add ("meloffCall10", "meloff_5");
		keyAudioList.Add ("meloffCall11", "jane_house_3_15");
		keyAudioList.Add ("meloffCall12", "meloff_6");
		keyAudioList.Add ("scene3Ending1", "michael_house_3_5");		
		keyAudioList.Add ("scene3Ending2", "michael_house_3_6");		
		keyAudioList.Add ("scene3Ending3", "jane_house_3_16");
		keyAudioList.Add ("scene3Ending4", "michael_house_3_7");		
		keyAudioList.Add ("scene3Ending5", "jane_house_3_17");
		//text house 4
		keyAudioList.Add ("dizzy3", "jane_house_4_1");
		keyAudioList.Add ("paulaPhoneCall2_1", "paula_house_4_1");
		keyAudioList.Add ("paulaPhoneCall2_2", "jane_house_4_2");
		keyAudioList.Add ("paulaPhoneCall3_1", "paula_house_4_2");
		keyAudioList.Add ("paulaPhoneCall3_2", "paula_mum_1");
		keyAudioList.Add ("paulaPhoneCall3_3", "paula_house_4_3");
		keyAudioList.Add ("paulaPhoneCall3_4", "paula_mum_2");
		keyAudioList.Add ("paulaPhoneCall3_5", "paula_house_4_4");
		keyAudioList.Add ("amnesia1", "jane_house_4_3");
		keyAudioList.Add ("amnesia2", "jane_house_4_4");
		keyAudioList.Add ("amnesia3", "jane_house_4_5");
		keyAudioList.Add ("amnesia4", "jane_house_4_6");
		keyAudioList.Add ("paulaPills1", "paula_house_4_5");
		keyAudioList.Add ("paulaPills2", "jane_house_4_7");
		keyAudioList.Add ("paulaPills3", "paula_house_4_6");
		keyAudioList.Add ("paulaPills4", "jane_house_4_8");
		keyAudioList.Add ("paulaPills5", "jane_house_4_9");
		keyAudioList.Add ("paulaPills6", "jane_house_4_10");
		keyAudioList.Add ("hidePills", "jane_house_4_11");
		keyAudioList.Add ("freshWater1", "paula_house_4_7");
		keyAudioList.Add ("freshWater2", "jane_house_4_12");
		keyAudioList.Add ("freshWater3", "paula_house_4_8");
		keyAudioList.Add ("freshWater4", "jane_house_4_13");
		keyAudioList.Add ("box", "jane_house_4_14");
		keyAudioList.Add ("ativan", "jane_house_4_15");
		keyAudioList.Add ("haldol", "jane_house_4_16");
		keyAudioList.Add ("wrongPills", "jane_house_4_17");
		keyAudioList.Add ("box2", "jane_house_4_18");
		keyAudioList.Add ("theory4", "jane_house_4_19");
		keyAudioList.Add ("phoneDefault", "jane_house_4_20");
		keyAudioList.Add ("information3_1", "jane_house_4_21");
		keyAudioList.Add ("information3_2", "information_4");
		keyAudioList.Add ("information3_3", "jane_house_4_22");
		keyAudioList.Add ("warderobe", "jane_house_4_23");
		keyAudioList.Add ("brotherCall1", "information_3");
		keyAudioList.Add ("brotherCall2", "eleanor_1");
		keyAudioList.Add ("brotherCall3", "jane_house_4_24");
		keyAudioList.Add ("brotherCall4", "eleanor_2");
		keyAudioList.Add ("brotherCall5", "jane_house_4_25");
		keyAudioList.Add ("brotherCall6", "eleanor_3");
		keyAudioList.Add ("brotherCall7", "jane_house_4_26");
		keyAudioList.Add ("brotherCall8", "eleanor_4");
		keyAudioList.Add ("brotherCall9", "jane_house_4_27");
		keyAudioList.Add ("brotherCall10", "eleanor_5");
		keyAudioList.Add ("brotherCall11", "michael_house_4_1");
		keyAudioList.Add ("janeCought1", "michael_house_4_2");
		keyAudioList.Add ("janeCought2", "jane_house_4_28");
		keyAudioList.Add ("janeCought3", "michael_house_4_3");
		keyAudioList.Add ("janeCought4", "jane_house_4_29");
		keyAudioList.Add ("janeCought5", "michael_house_4_4");
		keyAudioList.Add ("haldol2_1", "jane_house_4_30");
		keyAudioList.Add ("haldol2_2", "michael_house_4_5");
		keyAudioList.Add ("haldol2_3", "jane_house_4_31");
		keyAudioList.Add ("haldol2_4", "michael_house_4_6");
		keyAudioList.Add ("haldol2_5", "jane_house_4_32");
		keyAudioList.Add ("haldol2_6", "michael_house_4_7");
		keyAudioList.Add ("haldol2_7", "jane_house_4_33");
		keyAudioList.Add ("haldol2_8", "michael_house_4_8");
		keyAudioList.Add ("haldol2_9", "jane_house_4_34");
		keyAudioList.Add ("haldol2_10", "michael_house_4_9");
		keyAudioList.Add ("haldol2_11", "jane_house_4_35");
		keyAudioList.Add ("visit1", "jane_house_4_36");
		keyAudioList.Add ("visit2", "michael_house_4_10");
		keyAudioList.Add ("theory5", "jane_house_4_37");
		keyAudioList.Add ("daughterDead1", "jane_house_4_38");
		keyAudioList.Add ("daughterDead2", "michael_house_4_11");
		keyAudioList.Add ("daughterDead3", "jane_house_4_39");
		keyAudioList.Add ("daughterDead4", "michael_house_4_12");
		keyAudioList.Add ("daughterDead5", "jane_house_4_40");
		keyAudioList.Add ("daughterDead6", "michael_house_4_13");
		keyAudioList.Add ("daughterDead7", "jane_house_4_41");
		keyAudioList.Add ("daughterDead8", "michael_house_4_14");
		keyAudioList.Add ("daughterDead9", "jane_house_4_42");
		keyAudioList.Add ("daughterDead10", "michael_house_4_15");
		keyAudioList.Add ("daughterDead11", "jane_house_4_43");
		keyAudioList.Add ("janeDespaired1", "jane_house_5_1");
		keyAudioList.Add ("janeDespaired2", "jane_house_5_2");
		keyAudioList.Add ("janeDespaired3", "jane_house_5_3");
		keyAudioList.Add ("janeDespaired4", "jane_house_5_4");
		keyAudioList.Add ("janeDespaired5", "jane_house_5_5");
		keyAudioList.Add ("janeDespaired6", "jane_house_5_6");
		keyAudioList.Add ("michaelPaula1", "michael_house_5_1");
		keyAudioList.Add ("michaelPaula2", "paula_house_5_1");
		keyAudioList.Add ("michaelPaula3", "michael_house_5_2");
		keyAudioList.Add ("michaelPaula4", "paula_house_5_2");
		keyAudioList.Add ("michaelPaula5", "michael_house_5_3");
		keyAudioList.Add ("michaelPaula6", "paula_house_5_3");
		keyAudioList.Add ("michaelPaula7", "michael_house_5_4");
		keyAudioList.Add ("michaelPaula8", "paula_house_5_4");
		keyAudioList.Add ("michaelPaula9", "michael_house_5_5");
		keyAudioList.Add ("michaelPaula10", "jane_house_5_7");
		keyAudioList.Add ("lie", "jane_house_5_8");
		keyAudioList.Add ("information4_1", "jane_house_5_9");
		keyAudioList.Add ("information4_2", "information_5");
		keyAudioList.Add ("information4_3", "jane_house_5_10");
		keyAudioList.Add ("dianeCall1", "diane_1");
		keyAudioList.Add ("dianeCall2", "jane_house_5_11");
		keyAudioList.Add ("dianeCall3", "diane_2");
		keyAudioList.Add ("dianeCall4", "jane_house_5_12");
		keyAudioList.Add ("dianeCall5", "diane_3");
		keyAudioList.Add ("dianeCall6", "jane_house_5_13");
		keyAudioList.Add ("dianeCall7", "diane_4");
		keyAudioList.Add ("dianeCall8", "jane_house_5_14");
		keyAudioList.Add ("dianeCall9", "diane_5");
		keyAudioList.Add ("dianeCall10", "jane_house_5_15");
		keyAudioList.Add ("dianeCall11", "jane_house_5_16");
		keyAudioList.Add ("paulaBlock1", "paula_house_5_5");
		keyAudioList.Add ("paulaBlock2", "jane_house_5_17");
		keyAudioList.Add ("paulaBlock3", "paula_house_5_6");
		keyAudioList.Add ("paulaBlock4", "jane_house_5_18");
		keyAudioList.Add ("vase", "jane_house_5_19");
	}
}
